/*
 * This Java source file was generated by the Gradle 'init' task.
 * Used to generate a sample JUnit test
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
